backend:
  name: git-gateway
  branch: main
  site_domain: eloquent-rugelach-5b440d.netlify.app

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "paginas"
    label: "Páginas do Site"
    files:
      - label: "ACAGRUP 2026 - Ilha dos Cavalos"
        name: "acagrup-2026"
        file: "acagrup-2026.md"
        fields:
          - {label: "Título da Página", name: "title", widget: "string"}
          - {label: "Classe CSS (Não mexer)", name: "main_class", widget: "hidden", default: "main-content"}
          - {label: "Layout (Não mexer)", name: "layout", widget: "hidden", default: "default"}
          - {label: "Conteúdo da Página", name: "body", widget: "markdown"}
          
      - label: "Documentos do Agrupamento"
        name: "documentos"
        file: "documentos.md"
        fields:
          - {label: "Título da Página", name: "title", widget: "string"}
          - {label: "Classe CSS (Não mexer)", name: "main_class", widget: "hidden", default: "main-content"}
          - {label: "Layout (Não mexer)", name: "layout", widget: "hidden", default: "default"}
          - {label: "Conteúdo da Página", name: "body", widget: "markdown"}